// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/store-redesign/FlashDeal.tsx": () => import("../components/mockups/store-redesign/FlashDeal.tsx"),
  "./components/mockups/store-redesign/MarketPulse.tsx": () => import("../components/mockups/store-redesign/MarketPulse.tsx"),
  "./components/mockups/store-redesign/PremiumNG.tsx": () => import("../components/mockups/store-redesign/PremiumNG.tsx")
};
